### ISSUE TITLE
Inline css

### ISSUE THREAD

**Issue by sdhiman20** [artf/grapesjs-plugin-export#1]
Hi,

How can I add inline css in newsletter on click export.
Now export newsletter generate internal css but i want inline css. 
Please help me regarding this.

Thanks,

**Comment by artf** [comment]
Check https://github.com/artf/grapesjs-preset-newsletter/blob/master/src/openExportCommand.js to see how I've done it inside the newsletter preset

**Comment by sdhiman20** [comment]
Thanks for Help this is nice example

**Comment by bharadwaj84** [comment]
Hi Team,

I have my own newsletter code imported to Grape JS with Internal CSS. When I click on view code the code is converted to inline. Is it possible to have my code as it is with internal

**Comment by shubhraneelatlas** [comment]
@artf How to do it in case of ReactJS?
const [editor, setEditor] = useState(null);

  useEffect(() => {
    const editor = grapesjs.init({
      container: '#editor',
      plugins: [gjsPresetNewsletter, thePlugin],
      pluginsOpts: {
        'gjsPresetNewsletter': {
          tableStyle: {width: '600px', padding: '10px 10px 10px 10px'}
        },
        thePlugin:{}
       
      }
    });
    setEditor(editor);

    
  
  }, [])
  

  return (
    <div className="App">
      <div id="editor">

      </div>
    </div>
  );
