### ISSUE TITLE
Export to ZIP HTML file mostly has no newlines

### ISSUE THREAD

**Issue by Cabji** [artf/grapesjs-plugin-export#9]
When I export to ZIP and then open the index.html file in a text editor, the file has no newlines for all the HTML code until the for (var i = 0, len = items.length; i < len; i++) { line.

it is annoying as the HTML code has to manually formatted.

**Comment by artf** [comment]
The index.html is smaller without unnecessary stuff so it's better from the performance perspective. If you need to beautify the content of your HTML in order to edit it, you should be able to do it with any available code text editor.
